name: Simple Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository's code

      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"  # This is a simple echo command
